export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

import { StoreProvider } from "./store/StoreProvider";

import './globals.css'
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <StoreProvider>
      <html lang="en" className={inter.className}>
        <body>{children}</body>
      </html>
    </StoreProvider>
  );
}
